### ISSUE TITLE
Mejora estructura winforms y dependencias de proyectos.

### ISSUE THREAD

**Issue by mysery** [tgc-utn/tgc-viewer#1]
Dependencias de proyectos, separación de ejemplos alumnos, tgcviewer y motor de gráfico.
- La idea es mejorar como esta hoy el IOC, sobre ejemplos alumnos, etc. evitar que se carguen todas las dll para la ejecución, realizarlo en demanda.
  Esto es prioridad para encarar la mejora en ejecución de ejemplos, etc.

**Comment by DNAngeluS** [comment]
Estaría bueno definir una lista de pasos para este issue, yo creo que puedo ayudar bastante, me pelié mucho con la carga de libs y demás cuando estuve trabajando el Framework en C++. De hecho re hice el modelo varias veces. Sin embargo no estoy muy familiarizado con como esta hecho en el TGCViewer, creo que en esto me podrías dar una mano vos que te metiste mas a fondo para hacer el motor de física.

**Comment by mysery** [comment]
@DNAngeluS este lo esta haciendo rene, ya esta bastante atacado en la rama develop

**Comment by DNAngeluS** [comment]
@rejurime dejo abierta la puerta entonces, si queres hacer una lista de issues en lo que necesitas una mano me puedo sumar al coding.

**Comment by mysery** [comment]
Así es. Podes hacerte check out del repo develop y jugar ahí. Rene vuelve
el domingo así que no se cuantos pendientes dejo

**Comment by rejurime** [comment]
Genial @DNAngeluS el jueves vas a TGC? porque si venis y esta @mysery podemos charlar un poco como encararlo. Por ahora lo que hice básicamente es tratar de separar todo lo que sea UI de lo que debería ser el Core del TGC.

Por ahora cree un proyecto nuevo TGC.Core y ataque GUIController... trate de achicar el malvado god object que es jeje y ahora hay un par de semi dioses mas especializados :stuck_out_tongue_closed_eyes:

**Comment by DNAngeluS** [comment]
@rejurime Si voy el jueves, estuve viendo un poco los commits y me parece que esta muy bien. Yo hice algo parecido cuando arme mi engine, trate de englobar parte de la funcionalidad de ese objeto en varios objetitos mas chicos. Igual hay tantos commits que me cuesta un poco ver todos los cambios por eso estaria bueno charlarlo.

**Comment by rejurime** [comment]
Ahí mande un pull request... no se si alguien lo mirara jeje pero de ultima el jueves lo charlamos y si les parece lo mando a la master y creamos issues mas chicas con todas las cosas que me faltan que son bastante :anguished:
