### ISSUE TITLE
Remover el uso de move en los ejemplos

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-viewer#107]
Muchos de los ejemplos aun usan los métodos de Move, MoveOrientedY, Rotate, etc. Estos métodos se valen del AutoTransformEnable activado y se tomo la decisión de por defecto este en false y en algún momento eliminar.

**Comment by LeandroJavierLaino** [comment]
Mi Leandro del futuro me va a odiar por auto-asignarme esto 🤦‍♂️  Pero lo voy a hacer.

**Comment by rejurime** [comment]
Me auto asigno también así vamos tocando entre los 2 porque sino son muchos jaja

**Comment by rejurime** [comment]
Aun quedan:
* EjemploColisionCamara
* EjemploMoveThirdPerson
* EjemploPicking
* EjemploCajas
* EjemploCilindro
* EjemploEsfera
* EjemploMultiDiffuseLights
* EjemploPointLight
* EjemploBatchPrimitives
* EjemploDisposeMesh
* EjemploDefault
* PlaySound3D
* GuiTest
