### ISSUE TITLE
En el ejemplo de Tutorial 3

### ISSUE THREAD

**Issue by AntonioDLC** [tgc-utn/tgc-viewer#108]
Me intrigaba por qué no andaban bien las colisiones.
Descubrí un fix rápido pero poco confiable porque es un misterio para mí el que ande.
Consiste en cambiar el orden de los parámetros en el método: classifyBoxBox(box1, box2).
Si le pasás edificios al box1 y el auto al box2 anda fenómeno.

Puse un breakpoint que se activaba si se producía una colisión, cambié los parámetros de lugar y hice una colisión que con el código original no sería detectada. Me saltó esto:
![badboundboxaxisalignedhandling](https://user-images.githubusercontent.com/31079227/44748817-17e74580-aae7-11e8-8ccd-6062592cf4fd.jpg)

Muestra que la coordenada Z mínima del box2 es -598 y la coordenada Z máxima es -770 (aprox)
Es decir, que la coordenada Z mínima del box2 es MAYOR a la coordenada Z máxima.
Por eso en el if(collision) falla al momento de verificar si hay algún nro N entre ambas Z's pues se piden dos condiciones imposibles de cumplir ( N < Z mínima verdadera y Z máxima verdadera < N).

¿Es posible que haya un error en el manejo de los axis-aligned bounding box y no se recalculen las coordenadas de los puntos máximos y mínimos correctamente?
(¿Capaz entendí mal el concepto de axis aligned bounding box?)

Me interesa la respuesta porque si hay un error en los TgcBoundingAxisAlignBox, prefiero evitarlos en el TP.

**Comment by ghost** [comment]
Buenas,
En principio es porque estas queriendo clasificar.  (si esta dentro, fuera, en borde etc.
En los casos de testeo de colisión es mas optimo hacer  testBoxBox(box1, box2).
En ese caso no depende del orden.
Saludos.
pd.: este tipo de consulta mejor hacela en el mail del grupo.
