### ISSUE TITLE
Agregar Bullet al Core de Group

### ISSUE THREAD

**Issue by LeandroJavierLaino** [tgc-utn/tgc-viewer#116]
Falta el Rigid Body Factory de Bullet, todo dentro del namespace "Mathematica" y el nuevo "TgcSimpleTerrain" que necesita este Factory. Es necesario para el correcto funcionamiento de Bullet dentro de Group, generar nuevo NuGet del Core con esto.

**Comment by rejurime** [comment]
Listo 😄
