### ISSUE TITLE
Magia con "Post build events"

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-viewer#14]
Ahora hay 2 "post buil events" para la copia de las carpetas media y alumnos media, ya que dichos recursos no son del TGC.Viewer. Antes accedian a la carpeta de otros proyectos con regla de rutas, eso era aun peor esta es una solucion un poco mas elegante y funcional pero... es magia oscura :stuck_out_tongue_winking_eye:

**Comment by rejurime** [comment]
Ya no se copia mas la Media de los Examples

**Comment by mysery** [comment]
Quedaron los Postbuild para los shaders, esto termina haciendo algo raro en el desarrollo y toqueteo. ver otra forma de hacerlo. directamente que vayan a x folder. en vez de existir en un build.
