### ISSUE TITLE
Permitir el load de ejemplos separado del ejemplos alumno

### ISSUE THREAD

**Issue by mysery** [tgc-utn/tgc-viewer#2]
Mejora en la ejecución de ejemplos, ejecución limpia o solo en pantalla completa, verificando facilidad de desarrollo.
- La idea de esto es permitir una agilidad en el desarrollo del alumno, que el proyecto cargado sea siempre el de el, con opción de pantalla completa o no.
- Permitir la ejecución de ejemplos de la cátedra en demanda por ejemplo apretando F1

**Comment by rejurime** [comment]
Ya existe el método Update que se hereda desde TGCExample pero aun no se invoca en el render loop.

**Comment by rejurime** [comment]
Se creo otro repositorio donde esta lo mínimo para que puedan hacer el tp.
- https://github.com/tgc-utn/tgc-group
