### ISSUE TITLE
Revisar ejemplos

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-viewer#21]
Hay que revisar estos ejemplos si estan correctos y ademas alguno faltan mejorar sutilezas como la posicion de la camara para que arranquen y se vea lo que se quiere mostrar... porque muchas veces por la mala ubicacion de la camara hasta que uno no se mueve no se entiende que tiene el ejemplo.

Ejemplos:
- Alphablending Framework
- AlphaBlending Manual
- Efecto Niebla
- EditableLand
- Dispose Mesh
- Dispose Mesh 2
- Dispose Mesh 3
- Emisor de Particulas
- Pack Level
- Workshop-ShadowMap
- Workshop-ParallaxOcclusion

**Comment by rejurime** [comment]
Los que son muy complicados o hay que hacer algo particular se pueden crear issues mas pequeñas.

**Comment by mysery** [comment]
Se cambia el valor de ReferenceAlpha a 50 (anterior 100)
Esto hacia que algunos valores de alpha no se apliquen. quizás habría que buscar una mejor valor o ver que poner.

**Comment by mysery** [comment]
Seguramente haya que re chequear. pero ya estaban todos.
