### ISSUE TITLE
Investigar SharpDX y TGC.Viewer

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-viewer#25]
Investigar como hacer para reemplazar el Managed DirectX (MDX) que tiene el TGC.Viewer por SharpDX aunque sea por la version de DirectX 9.
- http://sharpdx.org/
- http://sharpdx.org/wiki/
- https://github.com/sharpdx/SharpDX

**Comment by DNAngeluS** [comment]
Logre implementar el Device de Direct3D9 y parte de DirectSound el cual requiere mas investigación (Issue #59 )

TGC.Core hace uso directo de objetos de Managed DirectX 9 los cuales no existen en versiones posteriores de DirectX por lo cual no están implementadas en SharpDX como por ejemplo: Mesh.

**Comment by rejurime** [comment]
Que opinas @DNAngeluS sobre esto? sigue valiendo la pena intentarlo? o es preferible refactorizar un poco el fw? para que la migracion mas adelante sea mas facil...

**Comment by DNAngeluS** [comment]
@rejurime Creo que hay que intentarlo, pero hay que refactorizar. Si parece lo hablamos un poco mas a fondo, y fijamos Issues mas definidas, porque hay que separar varias cosas del framework para hacer la transición.

**Comment by rejurime** [comment]
Me parece genial 😉, si queres podemos hacer la migracion mas segmentada tal vez jeje porque yo achure bien a lo carnicero 😛 y capaz eso complico las cosas.

**Comment by DNAngeluS** [comment]
Si, no esta mal achurado igual, el tema es que esta acoplado TGC.Core a Managed directX (y hay que desacoplarlo.
