### ISSUE TITLE
Descargar en forma automatica los Media

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-viewer#29]
La herramienta debe poder descargar si se lo pide los media de internet, si llega a fallar la descarga o la conexión mostrar el enlace de donde hacerlo en forma manual y configurarlo en la ventana de configuración.

**Comment by rejurime** [comment]
Para descargar de Google Drive debería implementar el uso de la API de Google https://developers.google.com/api-client-library/dotnet/ y la verdad no creo que valga la pena.
@mysery y @DNAngeluS que opinan?

**Comment by mysery** [comment]
no, para mi que abra explorador con la carpeta y que ponga el link deberia
alcanzar.

2017-04-26 12:42 GMT-03:00 René Juan Rico Mendoza <notifications@github.com>
:

**Comment by DNAngeluS** [comment]
hmmmm, no podemos meterlo en un git aparte y que se haga un pull a pedido del alumno?

**Comment by rejurime** [comment]
Pero es lo mismo que ahora te abre el browser para descargarlo y la carpeta donde va. Solo tienen que mover el zip y descomprimirlo.
