### ISSUE TITLE
Inclusion del concepto del modelo logico.

### ISSUE THREAD

**Issue by mysery** [tgc-utn/tgc-viewer#3]
Separación de render, modelo logico (colisiones etc).
- Esto viene que hoy el render y update están mezclados dentro de los TGCGeometry. lo cual dificulta la separación de los conceptos update y render.
- Esto implicaría una separación de las estructuras de colisiones dentro de una de las geometrías o la separación de las instancias de render dentro de ellas. (esto asociado a la separación de "materiales" de este modelo. otro issue dentro del mliestone.)

Como idea general esta tarea busca tener por un lado el modelo logico para realizar update (nuevas posiciones, transformaciones, manejo de colisiones, etc.) y por otro el modelo de render (texturas, shaders y drawcalls)

**Comment by rejurime** [comment]
Ya existe el método Update que se hereda desde TGCExample pero aun no se invoca en el render loop.

**Comment by rejurime** [comment]
Ya se invoca en proyecto para los alumnos:
- https://github.com/tgc-utn/tgc-group
