### ISSUE TITLE
Actualizacion de guia TGC Viewer

### ISSUE THREAD

**Issue by mysery** [tgc-utn/tgc-viewer#45]
Luego de ir cerrando la nueva versión de TGC es necesario actualizar la documentación y los ejemplos para crear nuevos ejemplos creativos.

**Comment by rejurime** [comment]
Se migra al repositorio de la pagina así vamos viendo los documentos ahí y no acá :smile: 
- https://github.com/tgc-utn/tgc-utn.github.io
