### ISSUE TITLE
Bug en el aspect ratio al maximizar el ejemplo

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-viewer#47]
Cuando se maximiza el ejemplo, se ve mal... hay un problema ahí a resolver.

**Comment by rejurime** [comment]
Para maximizar el ejemplo: Ver -> Maximizar ejemplo

**Comment by mysery** [comment]
arreglado a medias.... T_T hay que ver bien si hay que hacer un reset. por ahora se actualiza el aspect ratio.
