### ISSUE TITLE
Actualizacion de ejemplos TGC Viewer

### ISSUE THREAD

**Issue by mysery** [tgc-utn/tgc-viewer#48]
Hoy muchos de los ejemplos no funcionan, o son pruebas de concepto que pueden reducirse en 1 ejemplo.
Hay que crear una lista completa de que ejemplos queremos tener en un futuro y corregirlos.

pd.: son asignados todos a esto, es una buena forma de practicar el nuevo TGC. (esto debe ser ejecutado al finalizar los últimos detalles de TGC y tener la versión mas estable.)

**Comment by rejurime** [comment]
- 2D (**DONE**)
  - Juntar los 2 ejemplos de Sprites (**DONE**)
- Directx
  - DirectXLight (Cambiar color por defecto) (**DONE**)
  - Crear más primitivas DX (**Nueva issue**)
- Light (Revisar cuales estan repetidos en shaders)
  - BumpMapping (revisar el entorno)
  - EnvironmentMap (Re hacerlo donde sea correcta su aplicación)
  - HDR Usar el de Mariano
  - Fusionar point light con skeletal point light (**DONE**)
- Others (No deberia existir esta categoria) (**Solo quedo TGCLogo**)
  - ModeloConAlpha (Agregarle un modificador para activar o desactivar el alpha) (**DONE**)
  - Batch Primitives (arreglar camara analizar si son utiles) (**DONE, no me convence mucho... verificar.**)
  - Batch PrimitivesDX (arreglar camara analizar si son utiles) (**DONE**)
  - Dispose (dejar uno... el mas mejor :smile: ) (**DONE**)
- Outdoor (**DONE**)
  - CrearHeightmapBasico (arreglar camara) (**DONE, refactor de lugar**)
- Revisar Math y Transformations (hay cosas parecidas) (**DONE, refactor de nombres**)
  - Agregar el brazo del robot (**DONE**)
  - TextureMapping (revisarlo porque no anda y ver si sirve que este) (**VOLÓ, DONE**)

Faltan revisar:
- Colisions
- Geometrics basic (**DONE**)
- SceneLoader (**DONE**)
- Shaders y PostProcesados
- Sound (**DONE**)
- Tutorial (**DONE**)

**Comment by mysery** [comment]
Revisando:
Geometrics basic **No habia notado que todo esta en ingles :P**
- Cajas: Se cambiaron y agregaron en un solo ejemplo, se agregaron comentarios.
- TgcCylinder: Se arreglo la cámara no se si tiene mucho sentido, tiene algunos bugs si no tiene autotranformsEnable.
- EjemploSkyBox: se va a mesh
- EjemploSphere: se arreglo.
- Plane wall, se arreglo la camara que habia quedado estatica.
- Crear quad (es muy similar a wall pero en concepto otra cosa)

**Comment by rejurime** [comment]
Che igual todos los ejemplos estan en ingles jajaja por lo menos las categorias y los nombres :stuck_out_tongue_winking_eye:

**Comment by mysery** [comment]
Viendo collision..... va a estar muy duro!

**Comment by rejurime** [comment]
Viendo tutoriales :)

**Comment by rejurime** [comment]
Veo... si las movemos a Core queda como que andan bien eh jajaja

**Comment by mysery** [comment]
bien bien no estan funcionando, pero es muchisimo codigo para analizar en el tiempo que nos queda.

**Comment by rejurime** [comment]
Claro por eso te preguntaba porque lo pasaste a Core y no las dejaste en Example, pero fue se vera para la próxima

**Comment by mysery** [comment]
**Done** Colisions
Falta solo realizar la clasificación de shaders y listo el pollo quedan los ejemplos aunque tengan aun algunos errores.

**Comment by mysery** [comment]
Se crea nueva issue con lo que falta.
