### ISSUE TITLE
Arreglar, mejorar o cambiar EjemploMoveSphereThirdPerson

### ISSUE THREAD

**Issue by mysery** [tgc-utn/tgc-viewer#53]

**Comment by mysery** [comment]
Volviendo a probar este ejemplo creo que se arreglo con el ultimo commit. @rejurime

**Comment by rejurime** [comment]
Pero que era lo que tenia este ejemplo? porque no fuiste muy descriptivo :stuck_out_tongue_winking_eye:

**Comment by mysery** [comment]
creo que no colisionaba. ahora si lo hace... quizás porque utilizaba el
equal en algún momento.

2017-04-23 16:19 GMT-03:00 René Juan Rico Mendoza <notifications@github.com>
:

**Comment by rejurime** [comment]
Una vez terminada la migración de todo a TGCGeometry deberíamos volver a probar si esto anda :stuck_out_tongue: .

**Comment by LeandroJavierLaino** [comment]
Este ejemplo funciona! se podria cerrar el issue!
