### ISSUE TITLE
Arreglar, mejorar o cambiar EjemploMoveElipsoidTriangleThirdPerson

### ISSUE THREAD

**Issue by mysery** [tgc-utn/tgc-viewer#55]

**Comment by LeandroJavierLaino** [comment]
Revisar el TriangleMeshCollider, puede que venga por este lado que el Issue #54 y #55 tengan problemas para calcular las colisiones con triangulos pero no hay problemas con Sphere o Box.

**Comment by LeandroJavierLaino** [comment]
Esta casi para cerrar este issue ver el branch de BulletExamples

**Comment by LeandroJavierLaino** [comment]
Los issues #54 y #55 se reemplazaron por ejemplos en Bullet, igualmente siguen existiendo solo que no son publicos.
