### ISSUE TITLE
Investigar Naudio o alternativas a DirectSound

### ISSUE THREAD

**Issue by DNAngeluS** [tgc-utn/tgc-viewer#59]
Investigar como cambiar las dependencias de DirectSound (deprecado) a una que no este atada a la arquitectura de Microsoft. Este paso es necesario ademas para independenciar el Framework de Managed DirectX.

Alternativas:
- `https://github.com/naudio/NAudio`
- `http://sharpdx.org/wiki/class-library-api/x3daudio`

**Comment by rejurime** [comment]
Voy a intentar ir por https://docs.microsoft.com/es-es/windows/desktop/xaudio2/xaudio2-apis-portal usando SharpDX http://sharpdx.org/wiki/class-library-api/xaudio2/.
Me pareció mejor que usar NAudio que opinas @DNAngeluS ?

**Comment by LeandroJavierLaino** [comment]
Nota de color como esta implementado ahora en el branch del issue, usa el DirectSound de SharpDX pero este esta deprecado segun los desarrolladores de SharpDX http://sharpdx.org/wiki/class-library-api/directsound/ . Voy a probar de pasar a xaudio o cualquier alternativa mas copada dentro de SharpDX
