### ISSUE TITLE
Ver necesidades e implementar TGCVector4

### ISSUE THREAD

**Issue by mysery** [tgc-utn/tgc-viewer#66]
cuando implementamos el math no se hizo completo para vector 4

**Comment by rejurime** [comment]
Con lo que tenemos ahora cubre para lo que lo usamos, pero podría ser bueno implementarlo todo, si queres lo hago @mysery vos estas para las cosas importantes jaja deja al mulo lo fácil :smile:

**Comment by rejurime** [comment]
@mysery ya tiene todas las firmas del DX Vector4 pero no esta implementado mas que lo que usamos, que decís? los dejamos en NotImplementedException? o implementamos como en los demás?

**Comment by mysery** [comment]
implementamos sobre la marcha. con que esten bien implementados los cast,
equals y hascode alcanza.
