### ISSUE TITLE
El build se debe hacer en la carpeta por defecto

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-viewer#7]
Actualmente, los proyectos generan sus compilados en la carpeta raiz... por defecto deberia ser en bin\Debug\ o bin\Release segun se este trabajando.

El problema de cambiar esto es que el TGC.Viewer tiene la ruta clavada donde va a buscar las dlls de Examples y Group para cargarlas en tiempo de ejecucion.

Esto hace que sea un caos de dlls y cosas compiladas por todos lados :stuck_out_tongue_closed_eyes:

**Comment by mysery** [comment]
Esto esta realizado, se crearon diferentes tareas así que cerramos.
