### ISSUE TITLE
Problema de nombres entre Geometry.TGCPlane y Mathematica.TGCPlane

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-viewer#70]
Problema de nombres entre Geometry.TGCPlane y Mathematica.TGCPlane, es muy molesto tenes que identificar a cada uno, hay que pensas un nombre que lo identifique... capaz TGCWall asi como esta TGCBox y no Cube... tal vez?

**Comment by rejurime** [comment]
Que opinan @mysery y @DNAngeluS ? 😃

**Comment by DNAngeluS** [comment]
Cuales son las diferencias principales entre ambas clases? como para poder ponerle un mejor nombre?

**Comment by ghost** [comment]
Como hablamos en el bodi, TGCPlane en realidad debería ser TGCQuad, con la posibilidad de definirse plano xy, yz, zx ... no mas.

**Comment by rejurime** [comment]
Tomo TGCQuad como referente? y que cosas buenas de TGCPlane le agrego? o nada vale la pena. 
https://github.com/tgc-utn/tgc-viewer/blob/master/TGC.Core/Geometry/TgcQuad.cs
https://github.com/tgc-utn/tgc-viewer/blob/master/TGC.Core/Geometry/TgcPlane.cs

**Comment by mysery** [comment]
de quad no hay mucho que rescatar.
de plane si pero quizas hacerlo mejor :P
lo importante es que el quad no tiene textura y eso se quejaba mariano el
otro dia.

2017-05-19 16:57 GMT-03:00 René Juan Rico Mendoza <notifications@github.com>
:
