### ISSUE TITLE
Tiene sentido ITransformObject

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-viewer#72]
Desde que decidimos quitar AutoTransform de TGC hace falta seguir manteniendo esta interfaz?

```c#
    /// <summary>
    ///     Interfaz genérica para permitir que se le apliquen transformaciones a un objeto
    /// </summary>
    public interface ITransformObject
```

https://github.com/tgc-utn/tgc-viewer/blob/master/TGC.Core/SceneLoader/ITransformObject.cs

**Comment by rejurime** [comment]
Capaz sigue teniendo sentido pero algunas firmas deberiamos volarlas 😛 salvo que se quiera mantener compatibilidad con lo viejo.

**Comment by mysery** [comment]
tiene el problema que si sacamos eso tendremos que cambiar todos los
examples y el loaderscene para que no use mas el autotransform.
si estaria bueno sacarla, o quizas dejar algunos metodos espesificos.
2017-05-19 17:24 GMT-03:00 René Juan Rico Mendoza <notifications@github.com>
:

**Comment by rejurime** [comment]
Las funcionalidades que tiene hoy en día son:

- TGCMatrix Transform { get; set; }
- bool AutoTransformEnable { get; set; }
- TGCVector3 Position { get; set; }
- TGCVector3 Rotation { get; set; }
- TGCVector3 Scale { get; set; }
- void Move(TGCVector3 v);
- void Move(float x, float y, float z);
- void MoveOrientedY(float movement);
- void GetPosition(TGCVector3 pos);
- void RotateX(float angle);
- void RotateY(float angle);
- void RotateZ(float angle);

**Comment by rejurime** [comment]
@mysery @DNAngeluS @Javier-Rotelli que opinan? me colgaron 😢

**Comment by rejurime** [comment]
Tal vez aca deberiamos quitar varios metodos y agregar el Update?

**Comment by Javier-Rotelli** [comment]
podriamos ver de sacarlos y anotar cuantos examples se rompen. en base a eso podemos estimar mejor que costo tendria hacer el cambio.

igual coincido en que lo mejor seria volarlos todos y dejar el update

**Comment by mysery** [comment]
Si lo sacamos de ultima podriamos hacer una util de creacion de matrices... entonces despues invocamos a eso en los examples.  ejemplo el moveOrientedY ...
