### ISSUE TITLE
Problema para cambiar el valor de una Property que es un Struct

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-viewer#73]
Tengo problemas para tener [Auto-Implemented Properties](https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/classes-and-structs/auto-implemented-properties) cuando el tipo de dato es un [Struct](https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/classes-and-structs/structs). Cuando le quiero poner un valor no me deja... la unica solucion que use fue crear un Field con el Struct y ahi si me deja modificarle el valor.

```c#
public struct TGCVector3
{
    private Vector3 dxVector3;
    public float Y
    {
        get { return this.dxVector3.Y; }
        set { this.dxVector3.Y = value; }
    }
}

#TGCBox
//Esto compila.
TGCVector3 rotation;
public void RotateY(float angle)
{
	rotation.Y += angle;
}

//Esto no compila.
TGCVector3 Rotation {set; get;}
public void RotateY(float angle)
{
	Rotation.Y += angle;
}
```

¿Alguna idea? es muy paja tener que definirlo a mano cuando se puede evitar 😝.

Estos links tienen info pero no logue llegar a una idea concreta, creeria que es porque el Struct se pasa por valor y no referencia y en el auto implement al querer hacer el set no puede modificarlo, pero no podria asegurarlo.

* https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/classes-and-structs/using-structs
* https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/classes-and-structs/how-to-know-the-difference-passing-a-struct-and-passing-a-class-to-a-method
* https://docs.microsoft.com/en-us/dotnet/articles/csharp/language-reference/keywords/value-types

**Comment by LeandroJavierLaino** [comment]
Por lo que vi rápido es por la naturaleza del Struct se considera como valor y cuando tiene algún Field Private no permite modificarlo. La única solución seria que lo definas como Public, si no definis que es C# lo considera como Private.

```
public struct TGCVector3
{
    public Vector3 dxVector3;
    public float Y
    {
        get { return this.dxVector3.Y; }
        set { this.dxVector3.Y = value; }
    }
}
```

**Comment by rejurime** [comment]
Pasa que la idea fue armar wrappers para los objetos primitivos de DX y que nadie pueda acceder a los mismos. Si pongo publico a Vector3 (DX) podrían puentear nuestros objetos 😢.

**Comment by LeandroJavierLaino** [comment]
Y porque usas un Struct en vez de un Class con atributos Private?
Si vos tenes un Class con atributos Private, eso no lo haria inmutable? 
salvo que vos definas metodos que modifiquen esos atributos no se pueden tocar.

**Comment by mysery** [comment]
Y porque usas un Struct en vez de un Class con atributos Private?
Cuestiones de memoria.
Si vos tenes un Class con atributos Private, eso no lo haria inmutable?
Si, pero no aplica tan asi para graficos.
salvo que vos definas metodos que modifiquen esos atributos no se pueden
tocar.
El problema esta en que el struct luego es utilizado en el vertexbuffer.
creo que rene ya habia investigado de esto. en un momento intentamos hacer
funcionar y pinchaba. ya no recuerdo como :P

2017-08-24 17:36 GMT-03:00 Leandro Javier Laiño <notifications@github.com>:

**Comment by DNAngeluS** [comment]
Perdon que caigo medio al voleo en esto pero mando un ejemplo de como estaba usando unos Structcs para definir tipos de VertexBuffers.

```
class CustomVertex
{
  /**
  * Position + Color vertex
  */
  public struct PositionColored
  {
      public Vector3 Position { get;  set;}
      public Color Color { get; set; }
      public PositionColored(Vector3 position, Color color)
      {
         Position = position;
         Color = color;
      }
   };
}
```
Eso compila (o al menos me compilaba) Lo que era clave es el constructor. No podes hacer un Struct que no tenga definido su constructor y ese constructor tiene que obligatoriamente asignarle valores a sus propiedades. **Ahora viene la fruta** pero me parece que esto así justamente porque esta definido como memoria estática entonces tiene que instanciar el espacio de memoria de esas variables.

**Comment by rejurime** [comment]
Lo tengo definido asi @DNAngeluS, el problema seria si quisiera algo asi usando tu Struct (o por lo menos eso recuerdo jaja):
```c#
#ClaseLoca
PositionColored Position {set; get;}
public void ChangeY(float y)
{
	Position.Y += y;
}
```

Me obliga a tener que definir:
```c#
#ClaseLoca
PositionColored position;
public void ChangeY(float angle)
{
	position.Y += angle;
}
```

**Comment by rejurime** [comment]
No se pudo encontrar una alternativa así que se dejo con la definición del atributo y después el accessor.
