### ISSUE TITLE
Que responsabilidades le dejamos a IRenderObject

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-viewer#76]
Hoy en dia existe la interfaz IRenderObject con los siguientes comportamientos:

```c#
bool AlphaBlend { get; set; }
void Render();
void Dispose();
```

Con estos estamos? hay que agregar:
* Init
* Update

**Comment by rejurime** [comment]
Por lo general los objectos que implementan IRenderObject inicializan en el constructor, pero podria hacerlo tal vez en el init aunque no se si todos deberian...

Lo mismo pasa con el Update, toda geometria deberia actualizar su modelo? o hay algunas que no?

**Comment by rejurime** [comment]
O tal vez el Update deberia ir a ITransformObject #72 y algo que se dibuja no tiene porque actualizar nada... ah ah ah 😝

**Comment by mysery** [comment]
No se si lo llamaria Render object. pero si agregaria el Init y Update. pero creo que deberia ser otro concepto como un objeto que el motor puede renderizar, como eso siempre decimos, init->update->render->dispose

**Comment by rejurime** [comment]
TGCObject? :stuck_out_tongue_winking_eye:

**Comment by rejurime** [comment]
Igual si hacemos eso capaz el AlphaBlend si queda al pedo, tiene sentido si va a salir por la pantalla y ahi si puede ser RenderObject jaja.
