### ISSUE TITLE
Problemas en algunos ejemplos con Sphere

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-viewer#79]
* EjemploMoveSphereTriangleThirdPerson (No detecta colision con el piso y se pasa).
* EjemploMoveElipsoidTriangleThirdPerson (No detecta colision con el piso y se pasa).
* EjemploEsfera (No se dibuja la esfera, si se pone ver boundingbox se dibuja).

**Comment by rejurime** [comment]
#53 #54 #55

**Comment by LeandroJavierLaino** [comment]
Los issues de colisiones el quilombo esta en que no colisiona con los triangulos o no los detecta como colisionadores, si colisiona contra los planos.

**Comment by LeandroJavierLaino** [comment]
Hay que checkear el AutoTransform del TGCSphere, posiblemente sea el porque no se dibujan las esferas =/

**Comment by LeandroJavierLaino** [comment]
Los issues #54 y #55 sufren de un bug que por algun motivo los triangulos los considera un unico grupo y genera una BoundingSphere por todos. Lo extraño es que no colisiona con el BoundingSphere del personaje.

**Comment by LeandroJavierLaino** [comment]
Los issues #54 y #55 se reemplazaron por ejemplos en Bullet, igualmente siguen existiendo solo que no son publicos.

**Comment by rejurime** [comment]
@LeandroJavierLaino no estaría entendiendo que paso con los ejemplos viejos, esta arreglados? los borraste? los ocultaste?
Ocultarlos y que sigan estando pero defectuosos no seria la idea, si vamos por el camino de reemplazarlos por Bullet vamos directamente a eso y eliminamos los viejos. Pero este camino implica ir comiendo todos los viejos ejemplo para darle forma a los nuevos usando Bullet.

**Comment by LeandroJavierLaino** [comment]
@rejurime dale limpio todo y armo un nuevo pull request
