### ISSUE TITLE
Problema con el update de la camara

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-viewer#82]
@mbanquiero descubrió que el preupdate con la cámara hace cosas raras.
@mysery vos seguro entendiste más para poder hacer mejor la descripción. Habias hablado de hacer un postupdate con un updateView() o algo de eso jeje.

**Comment by ghost** [comment]
El problema surge cuando el setCamera se realiza al final. El preUpdate() realiza la matriz de vista, pero al hacer el setCamera después de esto queda para el próximo frame. esto hace que la cámara tiemble.
Tendremos que hacer un preupdate solo para elapsedtime e input. y un postupdate para la view y proyección.

**Comment by LeandroJavierLaino** [comment]
Probé de hacer un PostUpdate que haga eso del un update del view y proyección dejando en el PreUpdate el update del input y el elapsed time, pero permaneció igual. 

Algo que si note es que la cámara tiembla únicamente cuando se realiza una rotación con el mouse, cuando te desplazas (WASD, Control y Space) no hace nada raro o por lo menos no parece que lo haga.

Lo que hice fue modificar el factor de rotación para que sea mas suavizado y no tan brusco, con eso se soluciona el tema de que tiemble la cámara. 

Debería probarlo un poco mas pero pareciese que con eso se soluciona.

**Comment by mbanquiero** [comment]
Gente, son 2 cosas distintas,

1- habia un error de codigo que actualizaba la matriz ANTES de cambiar 
la pos de la camara y eso provocaba un "tembleque", que entiendo que eso 
esta arreglado

2- ADemas la camara (si estamos hablando de la misma) esta implentada 
con un sistema de "spring", basado en un paper (que no tengo ahora), 
pero la idea es que la camara sigue al personaje como si estuviese 
agarrado con un resorte. Me parece que cuando mati y lea portaron el 
codigo no tuvieron en cuenta como seria "ese" resorte en cuanto a la 
rotacion de la camara (es decir en principio solo aplica a la posicion 
de la camara) Eso trae 2 problemas

     a- Que pasa si lo que cambia bruscamente es la orientacion de la 
camara.

     b- Como setear los parametros del resorte (el coeficiente de 
amortiguacion y el otro, uno responde a la velocidad y el otro a la 
aceleracion). El resultado es un sistema que puede llegar a ser 
inestable y/o oscilar con retroalimentacion positiva.

**Comment by LeandroJavierLaino** [comment]
Yo el tembleque lo encontre en el **TgcFPSCamera**, ya que se aplica en la mayoria de los ejemplos del Viewer, hay una forma de arreglarlo ya esta casi lista.

Hay un **TgcSpringThirdPersonCamera**, si bien existe en el Viewer no se implemento en ningún ejemplo, deberia probarlo a ver que es lo que hace realmente. 

Lo mas probable es que sea un tema de parametros como ocurre con la de FPS.
 
**TgcSpringThirdPersonCamera** habria que ponerla en alguno de los ejemplos solo para que no quede como codigo sin usar y que los alumnos la puedan aprovechar en los TPs.

**Comment by LeandroJavierLaino** [comment]
Se sumo el metodo PostUpdate que se deberia realizar al final de cada Update lo que realiza es un update de la Matrix de View y el Frustum de la camara, se incluyo en todos los ejemplos sin esto no funciona ninguno.
