### ISSUE TITLE
Revisar up vector de las camaras.

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-viewer#87]
Calcular el UpVector efectivo a partir de LookFrom y LookAt ya que esta "hardcode" como el vector (0,1,0).

El upVector debe ser perpendicular al vector que forman el LookFrom y el LookAt. Es por este motivo que la camara sufre inconcistencias al momento de moverse y rotar.

**Comment by LeandroJavierLaino** [comment]
Se calculo el correcto upVector a partir del LookAt en la clase TGCCamera y se elimino el metodo SetCamera del TGCFPSCamera.
